#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Regenerate firmware wire fixtures with the explicit host encoder."""
import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[3]


sys.path.insert(0, str(ROOT / "tools"))
from codeplug_wire import channel, manifest


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    fixtures = {}
    for name, filename, encode in (
        ('empty_manifest', 'empty', manifest),
        ('fm_channel', 'fm-repeater', lambda v: channel(v['channels'][0])),
        ('m17_channel', 'm17-directed', lambda v: channel(v['channels'][0])),
    ):
        document = json.loads((ROOT / 'examples/codeplug' / (filename + '.json')).read_text())
        fixtures[name] = encode(document)
    rendered = '// SPDX-License-Identifier: GPL-3.0-or-later\n// Generated by generate.py from published JSON examples.\n#pragma once\n'
    for name, data in fixtures.items():
        rendered += f'static const unsigned char {name}[] = {{\n'
        for start in range(0, len(data), 12):
            rendered += '    ' + ', '.join(f'0x{b:02x}' for b in data[start : start + 12]) + ',\n'
        rendered += '};\n'
    output = Path(__file__).with_name('golden.hpp')
    if args.check:
        assert output.read_text() == rendered, 'Regenerate golden.hpp after a contract change'
    else:
        output.write_text(rendered)


if __name__ == '__main__':
    main()
