// SPDX-License-Identifier: GPL-3.0-or-later
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import {
    CskBootloader,
    SlipDecoder,
    slipEncode,
    HELPER_SHA256
} from '../../companion/src/bootloader.mjs';
import { md5 } from '../../companion/src/md5.mjs';
import { DSP_SHA256 } from '../../companion/src/firmware-bundle.mjs';
import { createFlashBackup, parseFlashBackup } from '../../companion/src/flash-backup.mjs';
const helper = new Uint8Array(
    await readFile(new URL('../../companion/bootloader/burner_venus.bin', import.meta.url))
);
assert.equal(createHash('sha256').update(helper).digest('hex'), HELPER_SHA256);
const hex = bytes => Buffer.from(bytes).toString('hex');
for (const [text, expected] of [
    ['', 'd41d8cd98f00b204e9800998ecf8427e'],
    ['a', '0cc175b9c0f1b6a831c399e269772661'],
    ['abc', '900150983cd24fb0d6963f7d28e17f72'],
    ['message digest', 'f96b697d7cb7938d525a2f31aaf161d0'],
    ['abcdefghijklmnopqrstuvwxyz', 'c3fcd3d76192e4007dfb496cca67e13b']
]) {
    assert.equal(hex(md5(new TextEncoder().encode(text))), expected);
}
for (const length of [55, 56, 63, 64, 65, 4096]) {
    const data = Uint8Array.from({ length }, (_, i) => i & 255);
    assert.equal(hex(md5(data)), createHash('md5').update(data).digest('hex'));
}
const decoder = new SlipDecoder();

function decode(wire) {
    const frames = [];
    for (const byte of wire) {
        const frame = decoder.feed(byte);
        if (frame) {
            frames.push(frame);
        }
    }
    return frames;
}
assert.deepEqual(
    Array.from(slipEncode(Uint8Array.of(0xc0, 0xdb, 7))),
    [0xc0, 0xdb, 0xdc, 0xdb, 0xdd, 7, 0xc0]
);
assert.equal(decode(Uint8Array.of(99, 88, 0xc0, 1, 0xdb)).length, 0);
assert.deepEqual(Array.from(decode(Uint8Array.of(0xdc, 0xc0))[0]), [1, 0xc0]);
assert.equal(decode(Uint8Array.of(0xc0, 1, 0xdb, 0x42, 1, 0xc0)).length, 0);
assert.equal(decode(Uint8Array.from([0xc0, ...Array(75).fill(1), 0xc0])).length, 0);
assert.deepEqual(Array.from(decode(Uint8Array.of(0xc0, 4, 0xc0))[0]), [4]);

// This fake decodes requests and constructs responses independently of the
// production SLIP/parser. Expected raw commands are frozen from the pinned C
// layouts, not generated by the browser implementation.

function unframe(wire) {
    assert.equal(wire[0], 0xc0);
    assert.equal(wire.at(-1), 0xc0);
    const raw = [];
    for (let i = 1; i < wire.length - 1; i++) {
        if (wire[i] === 0xdb) {
            const next = wire[++i];
            assert.ok(next === 0xdc || next === 0xdd);
            raw.push(next === 0xdc ? 0xc0 : 0xdb);
        } else {
            raw.push(wire[i]);
        }
    }
    return Uint8Array.from(raw);
}

function frame(raw) {
    const wire = [0xc0];
    for (const byte of raw) {
        wire.push(...(byte === 0xc0 ? [0xdb, 0xdc] : byte === 0xdb ? [0xdb, 0xdd] : [byte]));
    }
    return Uint8Array.from([...wire, 0xc0]);
}

function flashBytes(address, length) {
    return Uint8Array.from({ length }, (_, index) => ((address + index) * 73 + 7) & 255);
}

class Port {
    constructor(options = {}) {
        this.options = options;
        this.commands = [];
        this.ram = [];
        this.closed = 0;
        if (options.allowWrites) {
            this.flash = flashBytes(0, 0x400000);
        }
        this.readable = new ReadableStream({ start: controller => (this.rx = controller) });
        this.writable = new WritableStream({ write: wire => this.write(wire) });
    }

    async open(options) {
        this.opened = options;
        if (this.options.opening) {
            await this.options.opening;
        }
        assert.equal(options.baudRate, 115200);
    }

    async close() {
        assert.ok(!this.readable.locked && !this.writable.locked);
        this.closed++;
    }

    write(wire) {
        const raw = unframe(wire);
        const view = new DataView(raw.buffer);
        const op = raw[1];
        const payload = raw.slice(8);
        assert.equal(raw[0], 0);
        assert.equal(view.getUint16(2, true), payload.length);
        this.commands.push(raw);
        const pv = new DataView(payload.buffer);
        let data = new Uint8Array();
        let value = 0;
        let error = 0;
        if (op === 8) {
            assert.equal(hex(raw), '000824000000000007071220' + '55'.repeat(32));
        } else if (op === 5) {
            assert.equal(hex(raw), '000510000000000044970000130000000008000000000000');
        } else if (op === 7) {
            const bytes = payload.slice(16);
            assert.equal(pv.getUint32(0, true), bytes.length);
            assert.equal(pv.getUint32(4, true), this.ram.length);
            assert.equal(
                view.getUint32(4, true),
                bytes.reduce((sum, byte) => sum ^ byte, 0xef)
            );
            this.ram.push(bytes);
        } else if (op === 6) {
            assert.equal(hex(raw), '00060800000000000000000000000000');
        } else if (op === 0x0f) {
            assert.equal(hex(raw), '000f08000000000000c2010000c20100');
        } else if (op === 0xf3) {
            assert.equal(hex(raw), '00f3000000000000');
            value = this.options.flashId ?? (this.options.badCapacity ? 0x1740ef : 0x1640ef);
        } else if (op === 0xf4) {
            assert.equal(hex(raw), '00f4000000000000');
            data = this.options.zeroId
                ? new Uint8Array(8)
                : Uint8Array.from([1, 2, 3, 4, 5, 6, 7, 8]);
            if (this.options.noId) {
                error = 1;
            }
            if (this.options.changedId) {
                data[0] ^= 1;
            }
        } else if (op === 0x0e) {
            const address = pv.getUint32(0, true);
            const length = pv.getUint32(4, true);
            assert.ok(length > 0 && length <= 64 && address + length <= 0x400000);
            if (this.options.silentRead) {
                return;
            }
            const count = this.options.empty
                ? 0
                : this.options.short
                  ? Math.min(length, 17)
                  : length;
            data = this.flash
                ? this.flash.slice(address, address + count)
                : flashBytes(address, count);
            if (this.options.corrupt) {
                data[0] ^= 1;
            }
        } else if (op === 0x13) {
            const address = pv.getUint32(0, true);
            const length = pv.getUint32(4, true);
            assert.equal(payload.length, 16);
            assert.equal(pv.getUint32(8, true), 0);
            assert.equal(pv.getUint32(12, true), 0);
            data = new Uint8Array(
                createHash('md5')
                    .update(
                        this.flash
                            ? this.flash.subarray(address, address + length)
                            : flashBytes(address, length)
                    )
                    .digest()
            );
            if (this.options.shortDigest) {
                data = data.subarray(0, 15);
            }
        } else if (this.options.allowWrites && op === 2) {
            assert.equal(payload.length, 16);
            assert.equal(view.getUint32(4, true), 0);
            const size = pv.getUint32(0, true);
            const blocks = pv.getUint32(4, true);
            const address = pv.getUint32(12, true);
            assert.equal(pv.getUint32(8, true), 4096);
            assert.equal(blocks, Math.ceil(size / 4096));
            assert.ok(size > 0 && address % 4096 === 0 && address + blocks * 4096 <= 0x400000);
            this.program = { size, blocks, address, sequence: 0 };
            this.flash.fill(255, address, address + blocks * 4096);
        } else if (this.options.allowWrites && op === 3) {
            const active = this.program;
            const bytes = payload.subarray(16);
            assert.equal(pv.getUint32(0, true), bytes.length);
            assert.equal(pv.getUint32(4, true), active.sequence);
            assert.equal(pv.getUint32(8, true), 0);
            assert.equal(pv.getUint32(12, true), 0);
            assert.equal(bytes.length, Math.min(4096, active.size - active.sequence * 4096));
            assert.equal(
                view.getUint32(4, true),
                bytes.reduce((sum, byte) => sum ^ byte, 0xef)
            );
            this.flash.set(bytes, active.address + active.sequence++ * 4096);
            if (this.options.dropWriteReply) {
                return;
            }
        } else if (this.options.allowWrites && op === 4) {
            assert.equal(hex(raw), '0004040000000000ff000000');
            assert.equal(this.program.sequence, this.program.blocks);
            if (this.options.corruptProgram) {
                this.flash[this.program.address] ^= 1;
            }
            if (this.options.failFinish) {
                error = 1;
            }
        } else {
            assert.fail('Unexpected or flash-mutating operation ' + op);
        }
        const response = new Uint8Array(10 + data.length);
        const rv = new DataView(response.buffer);
        response.set([1, op]);
        rv.setUint16(2, response.length - 8, true);
        rv.setUint32(4, value, true);
        response[8] = error;
        response[9] = error ? 1 : 0;
        response.set(data, 10);
        if (this.options.malformed && op === 0x0e) {
            rv.setUint16(2, 66, true);
        }
        const output = frame(response);
        if (this.options.split) {
            this.rx.enqueue(Uint8Array.of(99, 88));
            for (let index = 0; index < output.length; index += 3) {
                this.rx.enqueue(output.slice(index, index + 3));
            }
        } else {
            this.rx.enqueue(output);
        }
        if (this.options.delayWrite && op === 0x0e) {
            return new Promise(resolve => setTimeout(resolve, 20));
        }
    }
}
const connection = new CskBootloader();
const port = new Port({ split: true, short: true });
assert.equal((await connection.connect(port, helper)).chipId, '0102030405060708');
assert.deepEqual(Buffer.concat(port.ram.map(bytes => Buffer.from(bytes))), Buffer.from(helper));
assert.deepEqual(
    port.commands.map(raw => raw[1]),
    [8, 5, ...Array(19).fill(7), 6, 8, 15, 8, 243, 244, 244]
);
const progress = [];
assert.deepEqual(
    await connection.readRange(0x3b0000, 65, { progress: value => progress.push(value) }),
    flashBytes(0x3b0000, 65)
);
assert.equal(progress.at(-1).stage, 'verify');
assert.equal(hex(port.commands.find(raw => raw[1] === 0x0e)), '000e08000000000000003b0040000000');
for (const [offset, size] of [
    [-1, 1],
    [0, 0],
    [0x400000, 1],
    [0, 0x400001],
    [0.1, 5],
    [0, true]
]) {
    await assert.rejects(connection.readRange(offset, size), /bounds/);
}
await Promise.all([connection.close(), connection.close()]);
assert.equal(port.closed, 1);
const invalidHelper = helper.slice();
invalidHelper[0] ^= 1;
const unused = new Port();
await assert.rejects(connection.connect(unused, invalidHelper), /corrupt/);
assert.equal(unused.opened, undefined);
for (const option of ['empty', 'corrupt', 'malformed', 'silentRead']) {
    const bad = new Port({ [option]: true });
    await connection.connect(bad, helper);
    await assert.rejects(connection.readRange(0x3b0000, 10));
    assert.equal(bad.closed, 1);
    assert.equal(connection.ready, false);
}
for (const option of ['noId', 'zeroId']) {
    const missing = new Port({ [option]: true });
    assert.equal((await connection.connect(missing, helper)).chipId, null);
    assert.equal((await connection.readRange(0, 1)).length, 1);
    await connection.close();
}
const capacity = new Port({ badCapacity: true });
await assert.rejects(connection.connect(capacity, helper), /capacity/);
assert.equal(capacity.closed, 1);
const cancelling = new Port();
await connection.connect(cancelling, helper);
const abort = new AbortController();
await assert.rejects(
    connection.readRange(0, 1024, {
        signal: abort.signal,
        progress: value => {
            if (value.completed >= 128) {
                abort.abort();
            }
        }
    })
);
assert.equal(cancelling.closed, 1);
let opened;
const opening = new Promise(resolve => (opened = resolve));
const slow = new Port({ opening });
const connecting = connection.connect(slow, helper);
await new Promise(resolve => setTimeout(resolve, 10));
const closing = connection.close();
opened();
await assert.rejects(connecting, /closed/);
await closing;
assert.equal(slow.closed, 1);
const complete = new Port({ delayWrite: true });
const info = await connection.connect(complete, helper);
assert.equal((await connection.readRange(0, 65)).length, 65);
complete.options.delayWrite = false;
const full = await connection.readRange(0, 0x400000);
const backup = await createFlashBackup(info, full);
const restored = await parseFlashBackup(backup);
assert.deepEqual(restored.bytes, full);
assert.equal(restored.device.chip_id, info.chipId);
await assert.rejects(createFlashBackup(info, full.subarray(1)), /complete/);
const partial = JSON.parse(backup);
partial.size--;
await assert.rejects(parseFlashBackup(JSON.stringify(partial)), /incomplete/);
const damaged = JSON.parse(backup);
damaged.data_base64 = 'AA==' + damaged.data_base64.slice(4);
await assert.rejects(parseFlashBackup(JSON.stringify(damaged)));
await connection.close();
// Build an independent valid pair without relying on a previous target build.
const hash = bytes => createHash('sha256').update(bytes).digest('hex');
const dsp = new Uint8Array(
    await readFile(new URL('../../backends/c62/resources/dsp_firmware.bin', import.meta.url))
);
for (const offset of [0x46150, 0x461b4, 0x461f4]) {
    dsp.set([0x0c, 0x02, 0x1d, 0xf0, 0x3d, 0xf0], offset + 3);
}
assert.equal(hash(dsp), DSP_SHA256);
const identity = 'dev-' + 'a'.repeat(32);
const app = new Uint8Array(4101).fill(0xc0);
app.set(new TextEncoder().encode(identity + '\0'));
const pair = {
    format: 'oe3anc-ht-firmware',
    schema_version: 1,
    target: 'c62',
    flash_size: 0x400000,
    erase_size: 4096,
    release: {
        identity,
        label: 'development',
        commit: 'b'.repeat(40),
        source_sha256: 'a'.repeat(64)
    },
    images: [app, dsp].map((bytes, index) => ({
        role: index ? 'dsp' : 'application',
        offset: index * 0x100000,
        size: bytes.length,
        sha256: hash(bytes),
        data_base64: Buffer.from(bytes).toString('base64')
    }))
};
const pairText = JSON.stringify(pair);
const writeOptions = { acknowledged: true };
const writeOps = port => port.commands.filter(raw => [2, 3, 4].includes(raw[1]));
const updated = new Port({ allowWrites: true });
await connection.connect(updated, helper);
const beforeAck = updated.commands.length;
await assert.rejects(connection.updateFirmware(pairText), /acknowledgement/);
await assert.rejects(connection.restoreBackup(backup, { acknowledged: 1 }), /acknowledgement/);
for (const verifyAfterWrite of [null, 0, 1, 'false']) {
    await assert.rejects(
        connection.updateFirmware(pairText, { ...writeOptions, verifyAfterWrite }),
        /must be boolean/
    );
    await assert.rejects(
        connection.restoreBackup(backup, { ...writeOptions, verifyAfterWrite }),
        /must be boolean/
    );
}
for (const applicationOnly of [null, 0, 1, 'false']) {
    await assert.rejects(
        connection.updateFirmware(pairText, { ...writeOptions, applicationOnly }),
        /must be boolean/
    );
}
await assert.rejects(
    connection.restoreBackup(backup, { ...writeOptions, applicationOnly: true }),
    /cannot limit a full restore/
);
assert.equal(updated.commands.length, beforeAck);
assert.equal(await connection.updateFirmware(pairText, writeOptions), identity);
assert.ok(updated.commands.some(raw => raw[1] === 0x0e));
assert.ok(updated.commands.some(raw => raw[1] === 0x13));
const expected = flashBytes(0, 0x400000);
for (const [index, bytes] of [app, dsp].entries()) {
    const offset = index * 0x100000;
    expected.fill(255, offset, offset + Math.ceil(bytes.length / 4096) * 4096);
    expected.set(bytes, offset);
}
assert.deepEqual(updated.flash, expected); // Includes unchanged settings, calibration and every gap.
assert.deepEqual(
    writeOps(updated)
        .filter(raw => raw[1] === 2)
        .map(raw => hex(raw)),
    [
        '000210000000000005100000020000000010000000000000',
        '0002100000000000901f0700720000000010000000001000'
    ]
);
await connection.close();
for (const option of [
    'changedId',
    'flashId',
    'invalidPair',
    'cancelled',
    'frozenError',
    'objectReason'
]) {
    const target = new Port({ allowWrites: true });
    await connection.connect(target, helper);
    let input = pairText;
    let options = writeOptions;
    if (option === 'changedId') {
        target.options.changedId = true;
    }
    if (option === 'flashId') {
        target.options.flashId = 0x1640c8;
    }
    if (option === 'invalidPair') {
        const bad = structuredClone(pair);
        bad.images[1].offset = 0x3b0000;
        input = JSON.stringify(bad);
    }
    if (['cancelled', 'frozenError', 'objectReason'].includes(option)) {
        const reason =
            option === 'cancelled'
                ? 'cancelled'
                : option === 'frozenError'
                  ? Object.freeze(new Error('frozen cancellation'))
                  : Object.create(null);
        options = { ...writeOptions, signal: AbortSignal.abort(reason) };
    }
    await assert.rejects(
        connection.updateFirmware(input, options),
        error => error.flashMayHaveChanged === false
    );
    assert.equal(writeOps(target).length, 0);
    assert.equal(target.closed, 1);
}
for (const option of ['crossRadio', 'missingBackupId', 'noId']) {
    const target = new Port({ allowWrites: true, noId: option === 'noId' });
    await connection.connect(target, helper);
    const input = JSON.parse(backup);
    if (option === 'crossRadio') {
        input.device.chip_id = '1112131415161718';
    }
    if (option === 'missingBackupId') {
        input.device.chip_id = null;
    }
    await assert.rejects(
        connection.restoreBackup(JSON.stringify(input), {
            ...writeOptions,
            verifyAfterWrite: false
        }),
        error => error.flashMayHaveChanged === false
    );
    assert.equal(writeOps(target).length, 0);
    assert.equal(target.closed, 1);
}
for (const option of ['dropWriteReply', 'corruptProgram', 'failFinish', 'cancelDuringWrite']) {
    const target = new Port({ allowWrites: true, [option]: true });
    await connection.connect(target, helper);
    const cancel = new AbortController();
    await assert.rejects(
        connection.updateFirmware(pairText, {
            ...writeOptions,
            signal: cancel.signal,
            progress: value => {
                if (option === 'cancelDuringWrite' && value.stage === 'write') {
                    cancel.abort('stop writing');
                }
            }
        }),
        error => error.flashMayHaveChanged === true
    );
    assert.equal(target.closed, 1);
    assert.equal(connection.ready, false);
    if (option === 'dropWriteReply') {
        assert.equal(writeOps(target).filter(raw => raw[1] === 3).length, 1);
    }
}
const target = new Port({ allowWrites: true });
const sameRadio = await connection.connect(target, helper);
target.flash.fill(0x55);
assert.equal(await connection.restoreBackup(backup, writeOptions), restored.sha256);
assert.deepEqual(target.flash, full);
assert.equal(writeOps(target).filter(raw => raw[1] === 2).length, 1);
assert.equal(sameRadio.chipId, restored.device.chip_id);
await connection.close();
// Opting out suppresses both readback and its digest commands for update/restore.
for (const restoring of [false, true]) {
    const unverified = new Port({ allowWrites: true });
    await connection.connect(unverified, helper);
    const stages = [];
    const options = {
        ...writeOptions,
        verifyAfterWrite: false,
        progress: value => stages.push(value.stage)
    };
    const result = await (restoring
        ? connection.restoreBackup(backup, options)
        : connection.updateFirmware(pairText, options));
    assert.equal(result, restoring ? restored.sha256 : identity);
    assert.deepEqual(unverified.flash, restoring ? full : expected);
    assert.equal(writeOps(unverified).filter(raw => raw[1] === 2).length, restoring ? 1 : 2);
    assert.equal(
        unverified.commands.some(raw => [0x0e, 0x13].includes(raw[1])),
        false
    );
    assert.ok(stages.length);
    assert.ok(stages.every(stage => stage === 'write'));
    await connection.close();
}
// Status failures and cancellation remain failures with readback disabled.
for (const option of ['failFinish', 'cancelDuringWrite']) {
    const unverified = new Port({ allowWrites: true, [option]: true });
    await connection.connect(unverified, helper);
    const cancel = new AbortController();
    await assert.rejects(
        connection.updateFirmware(pairText, {
            ...writeOptions,
            verifyAfterWrite: false,
            signal: cancel.signal,
            progress: value => {
                if (option === 'cancelDuringWrite') {
                    cancel.abort('stop writing');
                }
            }
        }),
        error => error.flashMayHaveChanged === true
    );
    assert.equal(unverified.closed, 1);
}
// Application-only writes require the matching DSP already on the radio.
for (const verifyAfterWrite of [true, false]) {
    const application = new Port({ allowWrites: true });
    await connection.connect(application, helper);
    application.flash.set(dsp, 0x100000);
    const expected = application.flash.slice();
    expected.fill(255, 0, Math.ceil(app.length / 4096) * 4096);
    expected.set(app);
    const stages = [];
    assert.equal(
        await connection.updateFirmware(pairText, {
            ...writeOptions,
            applicationOnly: true,
            verifyAfterWrite,
            progress: value => stages.push(value.stage)
        }),
        identity
    );
    assert.deepEqual(application.flash, expected);
    assert.equal(writeOps(application).filter(raw => raw[1] === 2).length, 1);
    const digestAt = application.commands.findIndex(raw => raw[1] === 0x13);
    const eraseAt = application.commands.findIndex(raw => raw[1] === 2);
    assert.ok(digestAt < eraseAt);
    const digest = application.commands[digestAt];
    assert.equal(new DataView(digest.buffer).getUint32(8, true), 0x100000);
    assert.equal(new DataView(digest.buffer).getUint32(12, true), dsp.length);
    assert.equal(stages[0], 'check-dsp');
    if (!verifyAfterWrite) {
        assert.equal(application.commands.filter(raw => raw[1] === 0x13).length, 1);
        assert.equal(
            application.commands.some(raw => raw[1] === 0x0e),
            false
        );
    }
    await connection.close();
}
for (const mismatched of [true, false]) {
    const application = new Port({ allowWrites: true, shortDigest: !mismatched });
    await connection.connect(application, helper);
    if (!mismatched) {
        application.flash.set(dsp, 0x100000);
    }
    await assert.rejects(
        connection.updateFirmware(pairText, {
            ...writeOptions,
            applicationOnly: true,
            verifyAfterWrite: false
        }),
        error => {
            assert.match(
                error.message,
                mismatched ? /Existing DSP does not match/ : /Invalid flash digest/
            );
            return error.flashMayHaveChanged === false;
        }
    );
    assert.equal(writeOps(application).length, 0);
    assert.equal(application.closed, 1);
}
const cancelledDsp = new Port({ allowWrites: true });
await connection.connect(cancelledDsp, helper);
cancelledDsp.flash.set(dsp, 0x100000);
const cancelDsp = new AbortController();
await assert.rejects(
    connection.updateFirmware(pairText, {
        ...writeOptions,
        applicationOnly: true,
        verifyAfterWrite: false,
        signal: cancelDsp.signal,
        progress: value => {
            if (value.stage === 'check-dsp') {
                cancelDsp.abort('DSP check cancelled');
            }
        }
    }),
    error => error.flashMayHaveChanged === false
);
assert.equal(writeOps(cancelledDsp).length, 0);
assert.equal(cancelledDsp.closed, 1);
console.log(
    'PASS: verified paired update, preservation, acknowledged same-radio full restore, pre-write rejection and interrupted-write cleanup'
);
console.log(
    'PASS: optional post-flash readback for update/restore, boolean choice validation, exact programming/preservation and cancellation/status errors with verification skipped'
);
console.log(
    'PASS: application-only writes with matching DSP checked before erasure, DSP/settings preservation and mismatched/truncated-digest rejection even without post-flash readback'
);
console.log(
    'PASS: pinned CSK6 sequence, split SLIP, read bounds/integrity, missing ID, cancellation/cleanup and complete 4 MiB backup round trip'
);
