# SPDX-License-Identifier: GPL-3.0-or-later
if(CONFIG_HT_CSK_SPI)
  add_subdirectory(${ZEPHYR_HT_MODULE_DIR}/drivers/spi csk_spi)
endif()
if(CONFIG_HT_CSK_GPIO)
  add_subdirectory(${ZEPHYR_HT_MODULE_DIR}/drivers/gpio csk_gpio)
endif()
if(CONFIG_HT_CSK_ADC)
  add_subdirectory(${ZEPHYR_HT_MODULE_DIR}/drivers/adc csk_adc)
endif()
if(CONFIG_HT_BATTERY)
  add_subdirectory(battery)
endif()
if(CONFIG_HT_POWER)
  add_subdirectory(power)
endif()
if(CONFIG_HT_BK4819)
  add_subdirectory(${ZEPHYR_HT_MODULE_DIR}/drivers/bk4819 bk4819)
endif()
if(CONFIG_HT_AUDIO)
  add_subdirectory(audio)
endif()
if(CONFIG_HT_LVGL)
  add_subdirectory(ui)
endif()
zephyr_include_directories(${ZEPHYR_HT_MODULE_DIR}/include)
if(CONFIG_HT_M17_PROTOCOL)
  add_subdirectory(protocols/m17)
endif()
if(CONFIG_HT_CODEC2)
  add_subdirectory(protocols/codec2)
endif()
if(CONFIG_HT_FM OR CONFIG_HT_M17_MODE)
  add_subdirectory(modes)
endif()
if(CONFIG_HT_RADIO)
  add_subdirectory(radio)
endif()
if(CONFIG_HT_SETTINGS)
  add_subdirectory(settings)
endif()
if(CONFIG_HT_CHANNELS)
  add_subdirectory(channels)
endif()
if(CONFIG_HT_RESOURCE_DIAGNOSTICS)
  add_subdirectory(diagnostics)
endif()

if(CONFIG_HT_COMPANION)
  add_subdirectory(companion)
endif()
