# SPDX-License-Identifier: GPL-3.0-or-later
cmake_minimum_required(VERSION 3.20.0)
list(APPEND BOARD_ROOT ${CMAKE_CURRENT_SOURCE_DIR}/../..)
list(APPEND DTS_ROOT ${CMAKE_CURRENT_SOURCE_DIR}/../..)
if(BOARD STREQUAL "c62")
  include(../../cmake/dsp-image.cmake)
endif()
find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})
project(ht_codec2_tests LANGUAGES C CXX)
target_sources(app PRIVATE src/main.cpp)
target_include_directories(app PRIVATE ../../modules/protocols/codec2)
if(CONFIG_BOARD_C62)
  target_sources(app PRIVATE ../../backends/c62/memory.c)
  zephyr_compile_definitions(PSRAM_CHIP_SIZE=4)
endif()
