// SPDX-License-Identifier: GPL-3.0-or-later
// Generate fixtures with official libm17, NOT with the implementation under test.
// libm17 commit 07926d08ade8509f1ce55d0289f229ab44cbcf51.
#include "m17.h"
#include <stdio.h>

static void print_bytes(const char *name, const uint8_t *bytes, size_t count) {
    printf("static constexpr uint8_t %s[%zu] = {", name, count);
    for (size_t i = 0; i < count; ++i) {
        if (i % 12 == 0)
            printf("\n    ");
        printf("0x%02x%s", bytes[i], i + 1 == count ? "" : ", ");
    }
    printf("};\n");
}

static void print_frame(const char *name, const int8_t *symbols) {
    uint8_t bytes[48] = {0};
    for (size_t i = 0; i < 192; ++i) {
        uint8_t dibit = symbols[i] == 1 ? 0 : symbols[i] == 3 ? 1 : symbols[i] == -1 ? 2 : 3;
        bytes[i / 4] |= dibit << (6 - 2 * (i % 4));
    }
    print_bytes(name, bytes, sizeof(bytes));
}

int main(void) {
    puts("// SPDX-License-Identifier: GPL-3.0-or-later\n"
         "// Generated by generate.c with libm17 07926d08ade8509f1ce55d0289f229ab44cbcf51.\n"
         "// Source: OE3ANC; destination: @ALL; type: 5; metadata: zeros.\n"
         "#pragma once\n#include <stdint.h>");
    lsf_t link;
    set_LSF(&link, "OE3ANC", "@ALL", 5, NULL);
    print_bytes("voice_link", (const uint8_t *)&link, sizeof(link));
    int8_t symbols[192];
    gen_frame_i8(symbols, NULL, FRAME_LSF, &link, 0, 0);
    print_frame("lsf_frame", symbols);
    uint8_t payload[16];
    for (unsigned i = 0; i < 16; ++i)
        payload[i] = i;
    for (unsigned i = 0; i < 6; ++i) {
        gen_frame_i8(symbols, payload, FRAME_STR, &link, i, i | (i == 5 ? 0x8000 : 0));
        char name[16];
        snprintf(name, sizeof(name), "stream_%u", i);
        print_frame(name, symbols);
    }
    // A correctly channel-coded LSF with a deliberately wrong CRC.
    link.crc[1] ^= 1;
    gen_frame_i8(symbols, NULL, FRAME_LSF, &link, 0, 0);
    print_frame("bad_crc_lsf", symbols);
    // Independent addressing/CAN matrix; unchanged reference library.
    lsf_t broadcast[16], directed[16];
    for (unsigned can = 0; can < 16; ++can) {
        set_LSF(&broadcast[can], "OE3ANC", "@ALL", 5 | (can << 7), NULL);
        set_LSF(&directed[can], "OE3ANC", "OE1TEST", 5 | (can << 7), NULL);
    }
    print_bytes("broadcast_can_links", (const uint8_t *)broadcast, sizeof(broadcast));
    print_bytes("directed_can_links", (const uint8_t *)directed, sizeof(directed));
    gen_frame_i8(symbols, NULL, FRAME_LSF, &directed[15], 0, 0);
    print_frame("directed_can15_lsf", symbols);
    for (unsigned i = 0; i < 6; ++i) {
        gen_frame_i8(symbols, payload, FRAME_STR, &directed[15], i, i | (i == 5 ? 0x8000 : 0));
        char name[32];
        snprintf(name, sizeof(name), "directed_can15_stream_%u", i);
        print_frame(name, symbols);
    }
    return 0;
}
