#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate the paired companion protocol constants; --check detects drift."""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def outputs():
    contract = json.loads((ROOT / 'protocol/companion/contract.json').read_text())
    constants = {key.upper(): value for key, value in contract.items() if type(value) is int}
    for group, prefix in (
        ('messages', 'MSG'),
        ('flags', 'FLAG'),
        ('statuses', 'STATUS'),
        ('capabilities', 'CAP'),
        ('cps_states', 'CPS_STATE'),
        ('ui_screens', 'UI_SCREEN'),
        ('ui_keys', 'UI_KEY'),
    ):
        constants.update({prefix + '_' + name: value for name, value in contract[group].items()})
    screens = re.search(
        r'enum class UiScreen : uint8_t \{(.*?)\};',
        (ROOT / 'include/ht/ui_presentation.hpp').read_text(),
        re.S,
    )
    names = [
        re.sub(r'(?<!^)(?=[A-Z])', '_', name.strip()).upper()
        for name in screens.group(1).split(',')
        if name.strip()
    ]
    if contract['ui_screens'] != dict((name, i) for i, name in enumerate(names)):
        raise SystemExit('UiScreen disagrees with normative companion screen IDs')
    header = '// SPDX-License-Identifier: GPL-3.0-or-later\n// Generated by tools/companion_contract.py.\n#pragma once\n#include <stdint.h>\nnamespace ht { namespace companion {\n'
    header += ''.join(f'constexpr unsigned {key} = {value};\n' for key, value in constants.items())
    header += '} } // namespace ht::companion\n'
    javascript = '// SPDX-License-Identifier: GPL-3.0-or-later\n// Generated by tools/companion_contract.py.\n'
    javascript += ''.join(f'export const {key} = {value};\n' for key, value in constants.items())
    return {
        ROOT / 'include/ht/companion_contract.hpp': header,
        ROOT / 'companion/src/contract.mjs': javascript,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(
                    f'Stale protocol constants: {path}; run tools/companion_contract.py'
                )
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)


if __name__ == '__main__':
    main()
